mybatis:
  type-aliases-package: demos.model
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localHost/spring?useUnicode=true&characterEncoding=utf8
    username: root  
    password: root+
